const CoursesTypes = {
  SEARCH_COURSE: "SEARCH_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  SET_NEW_COURSE: "SET_NEW_COURSE",
  ADD_NEW_COURSE: "ADD_NEW_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  SET_LOADING: "SET_LOADING",
  STOP_LOADING: "STOP_LOADING",
  CHECKBOX_NEW_COURSE: "CHECKBOX_NEW_COURSE",
};

export default CoursesTypes;
